import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Gelasio } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { SmoothScroll } from "@/components/SmoothScroll";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const gelasio = Gelasio({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-gelasio",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("dark", "h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable, gelasio.variable)}
    >
      <body className="min-h-full flex flex-col">
        <SmoothScroll />
        {children}
        <script src="https://mcp.figma.com/mcp/html-to-design/capture.js" async></script>
      </body>
    </html>
  );
}
